// AUTO-GENERATED by scripts/sync-theme-presets.mjs.
// Add, remove, or rename sibling preset .css files, then run the normal
// build/import path. Do not edit this registry by hand.

export interface BentoThemeMeta {
  /** Stable storage id, also the value written to `data-bento-theme`. */
  id: string;
  /** Display name shown in the picker. Derived from the preset filename. */
  name: string;
  /** Hex value for the picker swatch's primary half. */
  brand60: string;
  /** Hex value for the picker swatch's secondary half. */
  neutral20: string;
}

/** The id used when a workspace has no `themeId` set. */
export const DEFAULT_THEME_ID = 'default';

export const BENTO_THEMES: BentoThemeMeta[] = [
  {
    id: 'default',
    name: 'Default',
    brand60: '#025768',
    neutral20: '#e5e1dd',
  },
  {
    id: 'antique',
    name: 'Antique',
    brand60: '#936400',
    neutral20: '#eedfca',
  },
  {
    id: 'forest',
    name: 'Forest',
    brand60: '#317d00',
    neutral20: '#d2e7cb',
  },
  {
    id: 'mauve',
    name: 'Mauve',
    brand60: '#9b5267',
    neutral20: '#f4dae0',
  },
  {
    id: 'mountain-meadow',
    name: 'Mountain Meadow',
    brand60: '#007e64',
    neutral20: '#cde7de',
  },
  {
    id: 'rosewater',
    name: 'Rosewater',
    brand60: '#c60648',
    neutral20: '#ffd6d9',
  },
  {
    id: 'teal',
    name: 'Teal',
    brand60: '#25778d',
    neutral20: '#cfe5ec',
  },
  {
    id: 'terracotta',
    name: 'Terracotta',
    brand60: '#a64300',
    neutral20: '#f9d9cc',
  },
];

export function getThemeMeta(id: string | undefined | null): BentoThemeMeta {
  if (!id) return BENTO_THEMES[0]!;
  return BENTO_THEMES.find((theme) => theme.id === id) ?? BENTO_THEMES[0]!;
}
