// AUTO-GENERATED by scripts/sync-theme-presets.mjs.
// Shipped theme metadata comes from @tale-ui/themes; sibling preset CSS files
// supply Bento-specific themes. Do not edit this registry by hand.

export type BentoThemeCollection = 'bento' | 'standard' | 'monochrome';

export interface BentoThemeMeta {
  /** Stable storage id, also the value written to `data-bento-theme`. */
  id: string;
  /** Display name shown in the picker. */
  name: string;
  /** Short package-provided description used by search and tooltips. */
  description: string;
  /** Picker group and source collection. */
  collection: BentoThemeCollection;
  /** Hex value for the picker swatch's primary half. */
  brand60: string;
  /** Hex value for the picker swatch's secondary half. */
  neutral20: string;
}

/** The id used when a workspace has no `themeId` set. */
export const DEFAULT_THEME_ID = 'default';

export const BENTO_THEMES: BentoThemeMeta[] = [
  {
    id: 'default',
    name: 'Default',
    description: 'Bento’s default workspace palette.',
    collection: 'bento',
    brand60: '#025768',
    neutral20: '#e5e1dd',
  },
  {
    id: 'standard-harbour',
    name: 'Harbour',
    description: 'Deep teal with a warm stone neutral.',
    collection: 'standard',
    brand60: '#025768',
    neutral20: '#e5e1dd',
  },
  {
    id: 'standard-lagoon',
    name: 'Lagoon',
    description: 'Clear cyan teal with a cool mineral neutral.',
    collection: 'standard',
    brand60: '#006a6b',
    neutral20: '#dde3e2',
  },
  {
    id: 'standard-blueprint',
    name: 'Blueprint',
    description: 'Confident blue with a crisp steel neutral.',
    collection: 'standard',
    brand60: '#215d9a',
    neutral20: '#dee2e6',
  },
  {
    id: 'standard-violet-dusk',
    name: 'Violet Dusk',
    description: 'Soft violet with a balanced slate neutral.',
    collection: 'standard',
    brand60: '#6552a3',
    neutral20: '#e2e0e5',
  },
  {
    id: 'standard-wildflower',
    name: 'Wildflower',
    description: 'Muted berry with a gently rosy neutral.',
    collection: 'standard',
    brand60: '#8f3d65',
    neutral20: '#e4e0e2',
  },
  {
    id: 'standard-terracotta',
    name: 'Terracotta',
    description: 'Earthy coral with a warm clay neutral.',
    collection: 'standard',
    brand60: '#9b3f35',
    neutral20: '#e5e0de',
  },
  {
    id: 'standard-amber-grove',
    name: 'Amber Grove',
    description: 'Burnished amber with a soft sand neutral.',
    collection: 'standard',
    brand60: '#8a5a0a',
    neutral20: '#e4e1dc',
  },
  {
    id: 'standard-fern',
    name: 'Fern',
    description: 'Leaf green with a quiet botanical neutral.',
    collection: 'standard',
    brand60: '#3b6b43',
    neutral20: '#dfe2de',
  },
  {
    id: 'monochrome-antique',
    name: 'Antique',
    description: 'Burnished ochre across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#936400',
    neutral20: '#eedfca',
  },
  {
    id: 'monochrome-forest',
    name: 'Forest',
    description: 'Fresh leaf green across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#317d00',
    neutral20: '#d2e7cb',
  },
  {
    id: 'monochrome-mauve',
    name: 'Mauve',
    description: 'Dusty rose across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#9b5267',
    neutral20: '#f4dae0',
  },
  {
    id: 'monochrome-mountain-meadow',
    name: 'Mountain Meadow',
    description: 'Lush green teal across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#007e64',
    neutral20: '#cde7de',
  },
  {
    id: 'monochrome-rosewater',
    name: 'Rosewater',
    description: 'Vivid rose across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#c60648',
    neutral20: '#ffd6d9',
  },
  {
    id: 'monochrome-teal',
    name: 'Teal',
    description: 'Cool blue teal across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#25778d',
    neutral20: '#cfe5ec',
  },
  {
    id: 'monochrome-terracotta',
    name: 'Terracotta',
    description: 'Rich burnt orange across the brand and neutral scales.',
    collection: 'monochrome',
    brand60: '#a64300',
    neutral20: '#f9d9cc',
  },
];

const LEGACY_THEME_ALIASES: Readonly<Record<string, string>> = {
  antique: 'monochrome-antique',
  forest: 'monochrome-forest',
  mauve: 'monochrome-mauve',
  'mountain-meadow': 'monochrome-mountain-meadow',
  rosewater: 'monochrome-rosewater',
  teal: 'monochrome-teal',
  terracotta: 'monochrome-terracotta',
};

export function getThemeMeta(id: string | undefined | null): BentoThemeMeta {
  const requestedId = id ?? DEFAULT_THEME_ID;
  const canonicalId = LEGACY_THEME_ALIASES[requestedId] ?? requestedId;
  return BENTO_THEMES.find((theme) => theme.id === canonicalId) ?? BENTO_THEMES[0]!;
}
